global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'scheduler'
    static_configs:
      - targets: ['scheduler:9090']

  - job_name: 'fetcher'
    static_configs:
      - targets: ['fetcher:9090']

  - job_name: 'result-handler'
    static_configs:
      - targets: ['result-handler:9090']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 